version: '4'

services:
  profittrailer:
    build: .
    restart: always
    ports:
      - "8081:8081/tcp"
    volumes:
      - /root/profittrailer:/app/ProfitTrailer
    environment:
      PT_VERSION: 2.5.21
